https://www.kaggle.com/datasets/bwandowando/rotten-tomatoesall-time-best-super-hero-movies

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, HistGradientBoostingRegressor
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.preprocessing import OrdinalEncoder


from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier

In [2]:
df_movies = pd.read_csv(r'movies.csv')

In [3]:
df_critics = pd.read_csv(r'critic_reviews.csv')

In [4]:
df_user_reviews = pd.read_csv(r'user_reviews.csv')

In [5]:
df_movies.head(20)

,movieId,movieTitle,movieYear,movieURL,movieRank,critic_score,audience_score
0,4517f650-c60a-4edc-b37e-9236213c2b93,Spider-Man: Into the Spider-Verse,2018,https://www.rottentomatoes.com/m/spider_man_in...,1,97%,94%
1,9ddacc49-1918-3722-b5d9-4a1fa6b9b2a3,The Incredibles,2004,https://www.rottentomatoes.com/m/the_incredibles,2,97%,75%
2,e1374d4d-19b0-31b2-a6cc-c4189f2b27ca,Black Panther,2018,https://www.rottentomatoes.com/m/black_panther...,3,96%,79%
3,27539355-4940-4c29-aaab-d3fe4dafa4ee,Spider-Man: Across the Spider-Verse,2023,https://www.rottentomatoes.com/m/spider_man_ac...,4,95%,94%
4,2da44bd6-2a22-3238-a139-a40ab1769550,Teenage Mutant Ninja Turtles: Mutant Mayhem,2023,https://www.rottentomatoes.com/m/teenage_mutan...,5,95%,90%
5,7b2bcd9a-359f-3ffd-bbbd-abe9e5ce3f9e,Avengers: Endgame,2019,https://www.rottentomatoes.com/m/avengers_endgame,6,94%,90%
6,19b3ce59-1a84-3c4c-8bcf-0cd5e9c88cbf,Logan,2017,https://www.rottentomatoes.com/m/logan_2017,7,93%,90%
7,6263201f-baf8-3312-a482-f8dec3edd662,The Dark Knight,2008,https://www.rottentomatoes.com/m/the_dark_knight,8,94%,94%
8,41ca006b-8820-379c-84fc-aaae870b37f6,Iron Man,2008,https://www.rottentomatoes.com/m/iron_man,9,94%,91%
9,aae65496-63fc-3abe-aa6b-aeec81862322,Superman: The Movie,1978,https://www.rottentomatoes.com/m/superman_the_...,10,94%,86%
10,4f15afc8-8852-3a4e-8285-1aac469e7a72,Smoking Causes Coughing,2022,https://www.rottentomatoes.com/m/smoking_cause...,11,94%,51%
11,23d9f355-c290-3b60-8534-543bcf5656fd,Wonder Woman,2017,https://www.rottentomatoes.com/m/wonder_woman_...,12,93%,83%
12,a5e462a4-3e04-3db8-8fc4-46ad1144edc7,Thor: Ragnarok,2017,https://www.rottentomatoes.com/m/thor_ragnarok...,13,93%,87%
13,37409a82-f3ab-3187-b0da-efeefa489456,Spider-Man: No Way Home,2021,https://www.rottentomatoes.com/m/spider_man_no...,14,93%,98%
14,487e9820-001e-3da7-b47b-37003a7d7bc9,Incredibles 2,2018,https://www.rottentomatoes.com/m/incredibles_2,15,93%,84%
15,161dddb8-84c7-3ded-b9ed-0b2381422464,Spider-Man 2,2004,https://www.rottentomatoes.com/m/spiderman_2,16,93%,82%
16,9510a895-440a-37d7-aa67-9f456126a2ab,Spider-Man: Homecoming,2017,https://www.rottentomatoes.com/m/spider_man_ho...,17,92%,87%
17,4865d1c4-d511-3596-b848-7d57f86841e6,Guardians of the Galaxy,2014,https://www.rottentomatoes.com/m/guardians_of_...,18,92%,92%
18,a5479658-16f1-3325-a16a-4181d84a215a,RoboCop,1987,https://www.rottentomatoes.com/m/1017712-robocop,19,92%,84%
19,f362b9f5-57e0-3021-a310-ececbcf2f49f,Marvel's the Avengers,2012,https://www.rottentomatoes.com/m/marvels_the_a...,20,91%,91%

In [6]:
df_movies.columns

Index(['movieId', 'movieTitle', 'movieYear', 'movieURL', 'movieRank',
       'critic_score', 'audience_score'],
      dtype='object')

In [7]:
df_critics.head()

,reviewId,creationDate,criticName,criticPageUrl,reviewState,isFresh,isRotten,isRtUrl,isTopCritic,publicationUrl,publicationName,reviewUrl,quote,scoreSentiment,originalScore,movieId
0,1912176,1966-07-30,Jennie Kermode,/critics/jennie-kermode,fresh,True,False,False,False,/critics/source/1869,Eye for Film,http://www.eyeforfilm.co.uk/reviews.php?id=7898,NaN,POSITIVE,4/5,7602d2ab-c9bc-3439-9cd6-d3a06e81728e
1,1895073,1998-08-21,Scott Nash,/critics/scott-nash,fresh,True,False,False,False,/critics/source/1465,Three Movie Buffs,http://www.threemoviebuffs.com/review/blade,It's stylish and fast-paced. It's also a lot o...,POSITIVE,3/4,4128b2f6-8c69-396a-a83d-0d44eb90e5f7
2,25507,2000-01-01,Roger Ebert,/critics/roger-ebert,fresh,True,False,False,True,/critics/source/67,Chicago Sun-Times,http://www.rogerebert.com/reviews/the-rocketee...,"You have to dial down, to return to an age of ...",POSITIVE,3/4,01935e47-e735-30c3-b8bd-72a9dbbcfa8a
3,25508,2000-01-01,NaN,NaN,rotten,False,True,False,True,/critics/source/148,Empire Magazine,http://www.empireonline.com/reviews/reviewcomp...,Reaches for the skies but runs out of fuel.,NEGATIVE,2/5,01935e47-e735-30c3-b8bd-72a9dbbcfa8a
4,25509,2000-01-01,Joe Brown,/critics/joe-brown,fresh,True,False,False,True,/critics/source/474,Washington Post,http://www.washingtonpost.com/wp-srv/style/lon...,"Based on a comic book, deliciously corny but n...",POSITIVE,NaN,01935e47-e735-30c3-b8bd-72a9dbbcfa8a

In [8]:
df_user_reviews.head()

,movieId,rating,quote,reviewId,isVerified,isSuperReviewer,hasSpoilers,hasProfanity,score,creationDate,userDisplayName,userRealm,userId
0,13905397-4673-3e05-954d-8840645bebc2,1.0,"Did.Not.Like.\n\nThis movie was boring, overse...",NaN,False,False,False,False,1.0,2001-03-07,NaN,RT,901245019
1,13905397-4673-3e05-954d-8840645bebc2,4.5,[font=Arial]i never read the original story. ...,NaN,False,False,False,False,4.5,2002-03-08,NaN,RT,901245679
2,a2b255da-eb4d-3436-804b-fbe7b8732097,3.5,[left][b][font=Book Antiqua]xxxxx[/font][/b][/...,NaN,False,False,False,False,3.5,2002-09-03,NaN,RT,900608936
3,94a040f3-e1db-33b0-b7aa-6187e1406d21,2.0,"Art films can't center around gigantic, green ...",NaN,False,False,False,False,2.0,2003-01-21,NaN,RT,900592542
4,df35d67b-c89e-30fa-bff5-c31006cc6ae4,3.5,"dude, X-men 2 rocks! better then the first one...",NaN,False,False,False,False,3.5,2003-05-02,NaN,RT,900659519

In [9]:
# Step 1: Merge df_movies with df_critics on movieId
merged_df = pd.merge(df_movies, df_critics, on='movieId')

In [10]:
merged_df.head()

,movieId,movieTitle,movieYear,movieURL,movieRank,critic_score,audience_score,reviewId,creationDate,criticName,...,isFresh,isRotten,isRtUrl,isTopCritic,publicationUrl,publicationName,reviewUrl,quote,scoreSentiment,originalScore
0,4517f650-c60a-4edc-b37e-9236213c2b93,Spider-Man: Into the Spider-Verse,2018,https://www.rottentomatoes.com/m/spider_man_in...,1,97%,94%,2535772,2018-11-28,Sebastian Zavala Kahn,...,True,False,False,False,/critics/source/2840,Me gusta el cine,http://www.viveelcine.com/critica-spider-man-u...,Visually spectacular and unexpectedly emotiona...,POSITIVE,4/5
1,4517f650-c60a-4edc-b37e-9236213c2b93,Spider-Man: Into the Spider-Verse,2018,https://www.rottentomatoes.com/m/spider_man_in...,1,97%,94%,2535773,2018-11-28,Kirsten Acuna,...,True,False,False,False,/critics/source/3214,Insider,https://www.thisisinsider.com/spider-man-into-...,"""Spider-Man Into the Spider-Verse,"" feels like...",POSITIVE,A
2,4517f650-c60a-4edc-b37e-9236213c2b93,Spider-Man: Into the Spider-Verse,2018,https://www.rottentomatoes.com/m/spider_man_in...,1,97%,94%,2535774,2018-11-28,Molly Freeman,...,True,False,False,False,/critics/source/1647,Screen Rant,https://screenrant.com/spiderman-spider-verse-...,Spider-Man: Into the Spider-Verse delivers a f...,POSITIVE,4.5/5
3,4517f650-c60a-4edc-b37e-9236213c2b93,Spider-Man: Into the Spider-Verse,2018,https://www.rottentomatoes.com/m/spider_man_in...,1,97%,94%,2535785,2018-11-28,Clayton Davis,...,True,False,False,False,/critics/source/2586,AwardsCircuit.com,http://www.awardscircuit.com/2018/11/28/film-r...,"The directing team of Bob Persichette, Peter R...",POSITIVE,4/4
4,4517f650-c60a-4edc-b37e-9236213c2b93,Spider-Man: Into the Spider-Verse,2018,https://www.rottentomatoes.com/m/spider_man_in...,1,97%,94%,2535789,2018-11-28,Mike Cecchini,...,True,False,False,False,/critics/source/2170,Den of Geek,https://www.denofgeek.com/us/movies/spider-man...,It's the kind of achievement that brings to mi...,POSITIVE,5/5

In [11]:
merged_df.columns

Index(['movieId', 'movieTitle', 'movieYear', 'movieURL', 'movieRank',
       'critic_score', 'audience_score', 'reviewId', 'creationDate',
       'criticName', 'criticPageUrl', 'reviewState', 'isFresh', 'isRotten',
       'isRtUrl', 'isTopCritic', 'publicationUrl', 'publicationName',
       'reviewUrl', 'quote', 'scoreSentiment', 'originalScore'],
      dtype='object')

In [12]:
merged_df = merged_df.drop(columns=['movieTitle', 'movieYear', 'movieURL', 'reviewId', 'criticName', 'criticPageUrl', 'isRtUrl', 'publicationUrl', 'publicationName', 'reviewUrl', 'quote'])

In [13]:
merged_df.head()

,movieId,movieRank,critic_score,audience_score,creationDate,reviewState,isFresh,isRotten,isTopCritic,scoreSentiment,originalScore
0,4517f650-c60a-4edc-b37e-9236213c2b93,1,97%,94%,2018-11-28,fresh,True,False,False,POSITIVE,4/5
1,4517f650-c60a-4edc-b37e-9236213c2b93,1,97%,94%,2018-11-28,fresh,True,False,False,POSITIVE,A
2,4517f650-c60a-4edc-b37e-9236213c2b93,1,97%,94%,2018-11-28,fresh,True,False,False,POSITIVE,4.5/5
3,4517f650-c60a-4edc-b37e-9236213c2b93,1,97%,94%,2018-11-28,fresh,True,False,False,POSITIVE,4/4
4,4517f650-c60a-4edc-b37e-9236213c2b93,1,97%,94%,2018-11-28,fresh,True,False,False,POSITIVE,5/5

In [14]:
df_user_reviews.head()

,movieId,rating,quote,reviewId,isVerified,isSuperReviewer,hasSpoilers,hasProfanity,score,creationDate,userDisplayName,userRealm,userId
0,13905397-4673-3e05-954d-8840645bebc2,1.0,"Did.Not.Like.\n\nThis movie was boring, overse...",NaN,False,False,False,False,1.0,2001-03-07,NaN,RT,901245019
1,13905397-4673-3e05-954d-8840645bebc2,4.5,[font=Arial]i never read the original story. ...,NaN,False,False,False,False,4.5,2002-03-08,NaN,RT,901245679
2,a2b255da-eb4d-3436-804b-fbe7b8732097,3.5,[left][b][font=Book Antiqua]xxxxx[/font][/b][/...,NaN,False,False,False,False,3.5,2002-09-03,NaN,RT,900608936
3,94a040f3-e1db-33b0-b7aa-6187e1406d21,2.0,"Art films can't center around gigantic, green ...",NaN,False,False,False,False,2.0,2003-01-21,NaN,RT,900592542
4,df35d67b-c89e-30fa-bff5-c31006cc6ae4,3.5,"dude, X-men 2 rocks! better then the first one...",NaN,False,False,False,False,3.5,2003-05-02,NaN,RT,900659519

In [15]:
df_user_reviews.columns

Index(['movieId', 'rating', 'quote', 'reviewId', 'isVerified',
       'isSuperReviewer', 'hasSpoilers', 'hasProfanity', 'score',
       'creationDate', 'userDisplayName', 'userRealm', 'userId'],
      dtype='object')

In [16]:
df_u_r=df_user_reviews.drop(columns=['reviewId', 'userDisplayName', 'userRealm', 'userId', 'quote'])

In [17]:
merged_df.reset_index(inplace=True)
df_u_r.reset_index(inplace=True)

In [18]:
df_u_r.head()

,index,movieId,rating,isVerified,isSuperReviewer,hasSpoilers,hasProfanity,score,creationDate
0,0,13905397-4673-3e05-954d-8840645bebc2,1.0,False,False,False,False,1.0,2001-03-07
1,1,13905397-4673-3e05-954d-8840645bebc2,4.5,False,False,False,False,4.5,2002-03-08
2,2,a2b255da-eb4d-3436-804b-fbe7b8732097,3.5,False,False,False,False,3.5,2002-09-03
3,3,94a040f3-e1db-33b0-b7aa-6187e1406d21,2.0,False,False,False,False,2.0,2003-01-21
4,4,df35d67b-c89e-30fa-bff5-c31006cc6ae4,3.5,False,False,False,False,3.5,2003-05-02

In [19]:
df_u_r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2224583 entries, 0 to 2224582
Data columns (total 9 columns):
 #   Column           Dtype
---  ------           -----
 0   index            int64
 1   movieId          object
 2   rating           float64
 3   isVerified       bool
 4   isSuperReviewer  bool
 5   hasSpoilers      bool
 6   hasProfanity     bool
 7   score            float64
 8   creationDate     object
dtypes: bool(4), float64(2), int64(1), object(2)
memory usage: 93.3+ MB

In [20]:
merged_df.head()

,index,movieId,movieRank,critic_score,audience_score,creationDate,reviewState,isFresh,isRotten,isTopCritic,scoreSentiment,originalScore
0,0,4517f650-c60a-4edc-b37e-9236213c2b93,1,97%,94%,2018-11-28,fresh,True,False,False,POSITIVE,4/5
1,1,4517f650-c60a-4edc-b37e-9236213c2b93,1,97%,94%,2018-11-28,fresh,True,False,False,POSITIVE,A
2,2,4517f650-c60a-4edc-b37e-9236213c2b93,1,97%,94%,2018-11-28,fresh,True,False,False,POSITIVE,4.5/5
3,3,4517f650-c60a-4edc-b37e-9236213c2b93,1,97%,94%,2018-11-28,fresh,True,False,False,POSITIVE,4/4
4,4,4517f650-c60a-4edc-b37e-9236213c2b93,1,97%,94%,2018-11-28,fresh,True,False,False,POSITIVE,5/5

In [22]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27142 entries, 0 to 27141
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           27142 non-null  int64
 1   movieId         27142 non-null  object
 2   movieRank       27142 non-null  int64
 3   critic_score    27142 non-null  object
 4   audience_score  27142 non-null  object
 5   creationDate    27142 non-null  object
 6   reviewState     27142 non-null  object
 7   isFresh         27142 non-null  bool
 8   isRotten        27142 non-null  bool
 9   isTopCritic     27142 non-null  bool
 10  scoreSentiment  27142 non-null  object
 11  originalScore   19413 non-null  object
dtypes: bool(3), int64(2), object(7)
memory usage: 1.9+ MB

In [23]:
merged_df.columns

Index(['index', 'movieId', 'movieRank', 'critic_score', 'audience_score',
       'creationDate', 'reviewState', 'isFresh', 'isRotten', 'isTopCritic',
       'scoreSentiment', 'originalScore'],
      dtype='object')

In [28]:
merged_df_sub = merged_df[['movieId', 'movieRank', 'critic_score']]

In [29]:
# Step 2: Merge the result with df_user_reviews on movieId
final_df = pd.merge(merged_df_sub, df_u_r, on='movieId')

In [ ]:
dfm = df_movies.drop(columns=['movieId', 'movieTitle', 'movieYear', 'movieURL'])

In [ ]:
dfm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   movieRank       100 non-null    int64
 1   critic_score    100 non-null    object
 2   audience_score  100 non-null    object
dtypes: int64(1), object(2)
memory usage: 2.5+ KB

In [ ]:
df